/**
 * The vocabulary a made-up workspace name is built from.
 *
 * Three lists, read in order, so a name is always adjective-noun-verbing:
 * `magical-otters-flexing`. Nothing here is a word werk understands; the shape
 * is chosen so that a person seeing one in `git branch` or `werk list` knows
 * immediately that nobody named it, and so that two of them are easy to tell
 * apart at a glance, which a digest is not.
 *
 * Every word is lowercase letters only, so any triple is a name a branch and a
 * directory can both carry, and short enough that all three together stay
 * inside a readable directory leaf. `test/workspace-name.test.ts` holds both of
 * those, because a single mistyped entry here would otherwise surface as a
 * workspace that cannot be made.
 *
 * The lists are the same length by coincidence rather than by rule. 64 each is
 * a quarter of a million names, which is far more than the retry in `create`
 * needs to find a free one.
 */
export const ADJECTIVES = [
  "amber",
  "ancient",
  "arcane",
  "balmy",
  "bashful",
  "brave",
  "breezy",
  "bright",
  "brisk",
  "bubbly",
  "candid",
  "cheerful",
  "chilly",
  "chipper",
  "clever",
  "cosmic",
  "cosy",
  "crimson",
  "curious",
  "dapper",
  "daring",
  "dizzy",
  "dreamy",
  "eager",
  "earnest",
  "elated",
  "fabled",
  "feisty",
  "fluffy",
  "gallant",
  "gentle",
  "giddy",
  "gilded",
  "glossy",
  "golden",
  "hazy",
  "hearty",
  "humble",
  "jaunty",
  "jolly",
  "keen",
  "kindly",
  "lively",
  "lucid",
  "lunar",
  "magical",
  "mellow",
  "merry",
  "mighty",
  "misty",
  "nimble",
  "noble",
  "plucky",
  "polite",
  "quaint",
  "quiet",
  "rustic",
  "silky",
  "sleepy",
  "solar",
  "stellar",
  "sunny",
  "tender",
  "vivid",
] as const;

export const NOUNS = [
  "acorns",
  "alpacas",
  "badgers",
  "beetles",
  "camels",
  "comets",
  "cranes",
  "crickets",
  "dolphins",
  "donkeys",
  "falcons",
  "ferrets",
  "finches",
  "foxes",
  "geese",
  "hedgehogs",
  "herons",
  "ibexes",
  "kestrels",
  "kettles",
  "koalas",
  "lanterns",
  "lemurs",
  "llamas",
  "lobsters",
  "magpies",
  "marmots",
  "martens",
  "mittens",
  "moles",
  "moths",
  "narwhals",
  "okapis",
  "otters",
  "owls",
  "oxen",
  "pandas",
  "pebbles",
  "pelicans",
  "penguins",
  "ponies",
  "puffins",
  "quokkas",
  "ravens",
  "robins",
  "seals",
  "shrews",
  "snails",
  "sparrows",
  "storks",
  "swallows",
  "swans",
  "swifts",
  "tapirs",
  "teapots",
  "thimbles",
  "urchins",
  "voles",
  "walruses",
  "whales",
  "wombats",
  "wrens",
  "yaks",
  "zebras",
] as const;

export const VERBINGS = [
  "ambling",
  "bouncing",
  "brewing",
  "bustling",
  "chatting",
  "chirping",
  "climbing",
  "coasting",
  "cooking",
  "dancing",
  "dashing",
  "dawdling",
  "dreaming",
  "drifting",
  "drumming",
  "exploring",
  "fiddling",
  "fishing",
  "flexing",
  "floating",
  "flying",
  "foraging",
  "gliding",
  "grinning",
  "hiking",
  "humming",
  "jesting",
  "jogging",
  "juggling",
  "jumping",
  "knitting",
  "larking",
  "leaping",
  "loafing",
  "lounging",
  "marching",
  "mingling",
  "munching",
  "napping",
  "orbiting",
  "paddling",
  "painting",
  "plotting",
  "pondering",
  "prancing",
  "rambling",
  "roaming",
  "rowing",
  "sailing",
  "scheming",
  "scouting",
  "shuffling",
  "singing",
  "skating",
  "sketching",
  "skipping",
  "snoozing",
  "soaring",
  "strolling",
  "strumming",
  "swimming",
  "tinkering",
  "wandering",
  "whistling",
] as const;
